#!/usr/bin/env python3
"""Regenerate sales_orders.csv and cases.yaml from catalog.py.

    python evaluations/metric_suite/build.py

Only the standard library and PyYAML are needed.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from catalog import (  # noqa: E402
    CASES,
    CASES_FILE,
    DATA_FILE,
    NOW,
    SUITE_NAME,
    generate_orders,
    load_orders,
    oracle_rows,
    write_orders,
)


class _NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


HEADER = """# Generated by evaluations/metric_suite/build.py from catalog.py; do not edit by hand.
# Expected rows come from a plain-Python oracle over sales_orders.csv, not from SQL.
"""


def render_cases() -> str:
    orders = load_orders()
    cases = []
    for case in CASES:
        gold = case.gold_plan()
        expected = ({"outcome": "refusal"} if gold is None else
                    {"outcome": "success", "rows": oracle_rows(orders, case)})
        entry = {"id": case.id, "category": case.category, "question": case.question,
                 "context": case.context, "gold": gold, "expected": expected}
        if case.note:
            entry["note"] = case.note
        cases.append(entry)
    document = {"suite": {"name": SUITE_NAME, "now": NOW.isoformat(), "timezone": "Asia/Shanghai",
                          "float_tolerance": 0.01}, "cases": cases}
    return HEADER + yaml.dump(document, Dumper=_NoAliasDumper, allow_unicode=True, sort_keys=False, width=120)


def main() -> int:
    write_orders(generate_orders(), DATA_FILE)
    CASES_FILE.write_text(render_cases(), encoding="utf-8")
    print(f"wrote {DATA_FILE.name} and {CASES_FILE.name} ({len(CASES)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
